# Generated by Django 6.0.4 on 2026-05-28 07:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='principal/')),
                ('message', models.TextField()),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='principal', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='schools.school')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='unique_affiliation_per_school')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schools.school')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['school', 'start_date'], name='website_eve_school__dda191_idx')],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facility_images/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='schools.school')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='unique_facility_per_school')],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('admission', 'Admission'), ('fees', 'Fees'), ('academics', 'Academics'), ('facilities', 'Facilities'), ('general', 'General')], default='general', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='schools.school')),
            ],
            options={
                'ordering': ['order', 'category'],
                'indexes': [models.Index(fields=['school', 'category'], name='website_faq_school__a22be0_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'question'), name='unique_faq_per_school')],
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('academic', 'Academic Block'), ('labs', 'Laboratories'), ('library', 'Library'), ('sports', 'Sports Facilities'), ('activities', 'Co-curricular'), ('admin', 'Administrative'), ('student_welfare', 'Student Welfare'), ('transport', 'Transport'), ('hostel', 'Hostel'), ('other', 'Other')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='infrastructure/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructures', to='schools.school')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'category'], name='website_inf_school__8a6661_idx')],
            },
        ),
        migrations.CreateModel(
            name='MandatoryPublicDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('general_info', 'General Information'), ('documents', 'Documents'), ('academics', 'Academics'), ('staff', 'Staff'), ('infrastructure', 'Infrastructure')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='mandatory_disclosure/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosures', to='schools.school')),
            ],
            options={
                'ordering': ['section', 'order'],
                'indexes': [models.Index(fields=['school', 'section'], name='website_man_school__1cd647_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'section', 'title'), name='unique_disclosure_per_school'), models.CheckConstraint(condition=models.Q(models.Q(('value', ''), ('value__isnull', True), _connector='OR'), ('file__isnull', True), _negated=True), name='disclosure_value_or_file_required')],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('content', models.TextField()),
                ('date_published', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Academics', 'Academics'), ('Events', 'Events'), ('Sports', 'Sports'), ('Community', 'Community'), ('General', 'General')], default='General', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='schools.school')),
            ],
            options={
                'ordering': ['-date_published'],
                'indexes': [models.Index(fields=['school', 'date_published'], name='website_new_school__50856d_idx'), models.Index(fields=['school', 'slug'], name='website_new_school__d3093a_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'slug'), name='unique_news_slug')],
            },
        ),
    ]
