# Generated by Django 6.0.4 on 2026-05-09 07:15

import apps.schools.models
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('logo', models.ImageField(blank=True, default='schools/default/logo.png', null=True, upload_to=apps.schools.models.school_logo_path)),
                ('accreditation', models.CharField(blank=True, max_length=255)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('social_media_links', models.JSONField(blank=True, default=dict)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='schools_sch_name_5d0cfd_idx'), models.Index(fields=['is_active'], name='schools_sch_is_acti_522730_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_school_name_case_insensitive'), models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_school_email_if_present')],
            },
        ),
    ]
