# Generated by Django 6.0.4 on 2026-05-24 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='cluster',
            index=models.Index(fields=['code'], name='schools_clu_code_61555f_idx'),
        ),
        migrations.AddIndex(
            model_name='cluster',
            index=models.Index(fields=['is_deleted'], name='schools_clu_is_dele_c32b57_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['subdomain'], name='schools_sch_subdoma_88d5d3_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['is_deleted'], name='schools_sch_is_dele_a610ec_idx'),
        ),
    ]
