# Generated by Django 6.0.4 on 2026-07-18 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_aboutschool_deleted_at_aboutschool_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aboutschool',
            constraint=models.UniqueConstraint(fields=('school',), name='unique_about_school_per_school'),
        ),
    ]
