# Generated by Django 6.0.4 on 2026-07-20 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('schools', '0001_initial'),
        ('timetables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherworkload',
            options={'ordering': ['teacher__name'], 'verbose_name': 'Teacher Workload', 'verbose_name_plural': 'Teacher Workloads'},
        ),
        migrations.AlterModelOptions(
            name='workingday',
            options={'ordering': ['display_order'], 'verbose_name': 'Working Day', 'verbose_name_plural': 'Working Days'},
        ),
        migrations.AlterUniqueTogether(
            name='workingday',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='teacherworkload',
            name='allow_overtime',
        ),
        migrations.RemoveField(
            model_name='teacherworkload',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='teacherworkload',
            name='max_consecutive_periods',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maximum consecutive teaching periods without a break.'),
        ),
        migrations.AlterField(
            model_name='teacherworkload',
            name='max_periods_per_day',
            field=models.PositiveSmallIntegerField(default=6, help_text='Maximum teaching periods allowed per day.'),
        ),
        migrations.AlterField(
            model_name='teacherworkload',
            name='max_periods_per_week',
            field=models.PositiveSmallIntegerField(default=36, help_text='Maximum teaching periods allowed per week.'),
        ),
        migrations.AlterField(
            model_name='teacherworkload',
            name='min_periods_per_day',
            field=models.PositiveSmallIntegerField(default=0, help_text='Minimum teaching periods expected per day.'),
        ),
        migrations.AlterField(
            model_name='teacherworkload',
            name='min_periods_per_week',
            field=models.PositiveSmallIntegerField(default=0, help_text='Minimum teaching periods expected per week.'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='day_code',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='is_half_day',
            field=models.BooleanField(default=False, help_text='Check if only part of the day is working.'),
        ),
        migrations.AlterField(
            model_name='workingday',
            name='is_working_day',
            field=models.BooleanField(default=True, help_text='Uncheck for holidays or weekly off.'),
        ),
        migrations.AddIndex(
            model_name='workingday',
            index=models.Index(fields=['school', 'academic_session'], name='tt_working__school__deae5c_idx'),
        ),
        migrations.AddIndex(
            model_name='workingday',
            index=models.Index(fields=['day_code'], name='tt_working__day_cod_cf70aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='workingday',
            constraint=models.UniqueConstraint(fields=('school', 'academic_session', 'day_code'), name='unique_working_day_per_session'),
        ),
    ]
