# Generated by Django 6.0.4 on 2026-06-13 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_alter_asset_options_alter_classroom_options_and_more'),
        ('timetables', '0002_alter_timetableentry_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='infrastructure.room'),
        ),
    ]
