# Generated by Django 6.0.4 on 2026-07-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_alter_teacherworkload_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherpreference',
            options={'ordering': ['teacher__name'], 'verbose_name': 'Teacher Preference', 'verbose_name_plural': 'Teacher Preferences'},
        ),
        migrations.RemoveField(
            model_name='teacherpreference',
            name='max_periods_per_day',
        ),
        migrations.RemoveField(
            model_name='teacherpreference',
            name='max_periods_per_week',
        ),
        migrations.RemoveField(
            model_name='teacherpreference',
            name='prefer_consecutive_periods',
        ),
        migrations.RemoveField(
            model_name='teacherpreference',
            name='preferred_free_day',
        ),
        migrations.RemoveField(
            model_name='teacherpreference',
            name='remarks',
        ),
        migrations.AddField(
            model_name='teacherpreference',
            name='maximum_free_gaps',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maximum free periods allowed between teaching periods in a day.'),
        ),
        migrations.AddField(
            model_name='teacherpreference',
            name='preferred_shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon')], help_text='Preferred teaching session.', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherpreference',
            name='avoid_first_period',
            field=models.BooleanField(default=False, help_text='Avoid teaching in the first period.'),
        ),
        migrations.AlterField(
            model_name='teacherpreference',
            name='avoid_gaps_between_classes',
            field=models.BooleanField(default=False, help_text='Try to avoid idle periods between classes.'),
        ),
        migrations.AlterField(
            model_name='teacherpreference',
            name='avoid_last_period',
            field=models.BooleanField(default=False, help_text='Avoid teaching in the last period.'),
        ),
        migrations.AlterField(
            model_name='teacherpreference',
            name='prefer_first_period',
            field=models.BooleanField(default=False, help_text='Prefer teaching in the first period.'),
        ),
        migrations.AlterField(
            model_name='teacherpreference',
            name='prefer_last_period',
            field=models.BooleanField(default=False, help_text='Prefer teaching in the last period.'),
        ),
    ]
