# Generated by Django 6.0.4 on 2026-07-21 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('schools', '0001_initial'),
        ('staff', '0005_alter_teacherattendance_options_and_more'),
        ('timetables', '0003_alter_teacherpreference_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectconstraint',
            options={'ordering': ['subject_requirement__school_class__display_order', 'subject_requirement__subject__name'], 'verbose_name': 'Subject Constraint', 'verbose_name_plural': 'Subject Constraints'},
        ),
        migrations.AlterModelOptions(
            name='subjectrequirement',
            options={'ordering': ['school_class__display_order', 'subject__name']},
        ),
        migrations.AlterModelOptions(
            name='teacheravailability',
            options={'ordering': ['teacher__employee_id', 'day', 'period'], 'verbose_name': 'Teacher Availability', 'verbose_name_plural': 'Teacher Availabilities'},
        ),
        migrations.RenameField(
            model_name='subjectrequirement',
            old_name='is_mandatory',
            new_name='is_compulsory',
        ),
        migrations.RenameField(
            model_name='subjectrequirement',
            old_name='practical_periods_per_week',
            new_name='lab_periods_per_week',
        ),
        migrations.AlterUniqueTogether(
            name='subjectrequirement',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teacheravailability',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subjectconstraint',
            name='min_periods_per_day',
        ),
        migrations.RemoveField(
            model_name='subjectconstraint',
            name='periods_per_week',
        ),
        migrations.RemoveField(
            model_name='subjectconstraint',
            name='requires_resource',
        ),
        migrations.RemoveField(
            model_name='subjectconstraint',
            name='requires_room',
        ),
        migrations.RemoveField(
            model_name='subjectconstraint',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='subjectconstraint',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='subjectconstraint',
            name='subject',
        ),
        migrations.AddField(
            model_name='subjectconstraint',
            name='preferred_time_slot',
            field=models.CharField(choices=[('ANY', 'Any'), ('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon')], default='ANY', max_length=10),
        ),
        migrations.AddField(
            model_name='subjectconstraint',
            name='priority',
            field=models.PositiveSmallIntegerField(default=5, help_text='Lower value indicates higher scheduling priority.'),
        ),
        migrations.AddField(
            model_name='subjectconstraint',
            name='spread_across_week',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subjectconstraint',
            name='subject_requirement',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_constraint', to='timetables.subjectrequirement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectrequirement',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Subject is shared between multiple classes/sections.'),
        ),
        migrations.AddField(
            model_name='subjectrequirement',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_requirements', to='academics.stream'),
        ),
        migrations.AddField(
            model_name='subjectrequirement',
            name='sub_stream',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subjectrequirement',
            name='theory_periods_per_week',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subjectconstraint',
            name='max_periods_per_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subjectconstraint',
            name='required_consecutive_periods',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'staff_role': 'Teaching'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_availabilities', to='staff.staff'),
        ),
        migrations.AddIndex(
            model_name='subjectrequirement',
            index=models.Index(fields=['school', 'academic_session', 'school_class'], name='tt_subject__school__10da87_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectrequirement',
            index=models.Index(fields=['stream'], name='tt_subject__stream__89e28c_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectrequirement',
            index=models.Index(fields=['subject'], name='tt_subject__subject_bd6fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='teacheravailability',
            index=models.Index(fields=['school', 'academic_session'], name='teacher_av_school_session_idx'),
        ),
        migrations.AddIndex(
            model_name='teacheravailability',
            index=models.Index(fields=['teacher', 'day'], name='teacher_av_teacher_day_idx'),
        ),
        migrations.AddIndex(
            model_name='teacheravailability',
            index=models.Index(fields=['teacher', 'is_available'], name='teacher_av_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='subjectrequirement',
            constraint=models.UniqueConstraint(fields=('school', 'academic_session', 'school_class', 'section', 'stream', 'sub_stream', 'subject'), name='unique_subject_requirement'),
        ),
        migrations.AddConstraint(
            model_name='teacheravailability',
            constraint=models.UniqueConstraint(fields=('school', 'academic_session', 'teacher', 'day', 'period'), name='unique_teacher_availability'),
        ),
        migrations.RemoveField(
            model_name='subjectrequirement',
            name='periods_per_day',
        ),
        migrations.RemoveField(
            model_name='subjectrequirement',
            name='periods_per_week',
        ),
    ]
