# Generated by Django 6.0.4 on 2026-07-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0004_alter_subjectconstraint_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectrequirement',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Priority for timetabling/scheduling.'),
        ),
        migrations.AddField(
            model_name='subjectrequirement',
            name='teachers_required',
            field=models.PositiveIntegerField(default=1, help_text='Number of teachers required for this subject requirement.'),
        ),
    ]
