# Generated by Django 6.0.4 on 2026-05-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='AccessControl',
        ),
    ]
