# Generated by Django 6.0.4 on 2026-05-09 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True)),
                ('aadhar_number', models.CharField(blank=True, help_text='Optional. Must be unique if provided.', max_length=12, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('current_joining_date', models.DateField(blank=True, null=True)),
                ('retirement_date', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='staff_profile/default.png', null=True, upload_to='staff_profile/')),
                ('staff_role', models.CharField(choices=[('Administrative', 'Administrative'), ('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching'), ('Support', 'Support')], default='Teaching', max_length=20)),
                ('employment_type', models.CharField(choices=[('Regular', 'Regular'), ('SSA', 'SSA'), ('Guest', 'Guest'), ('HKRNL', 'HKRNL'), ('NSQF', 'NSQF'), ('MDMWorker', 'MDM Worker'), ('Other', 'Other')], default='Regular', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('max_periods_per_week', models.PositiveIntegerField(default=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.posttype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='schools.school')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_subjects', to='academics.subject')),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['school', 'post_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassIncharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incharge', to='academics.section')),
                ('staff', models.ForeignKey(limit_choices_to={'staff_role': 'Teaching'}, on_delete=django.db.models.deletion.CASCADE, related_name='incharge_assignments', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('teacher', models.ForeignKey(limit_choices_to={'staff_role': 'Teaching'}, on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.classsubject')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academics.section')),
                ('teacher', models.ForeignKey(limit_choices_to={'staff_role': 'Teaching'}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='SanctionedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('total_posts', models.PositiveIntegerField(default=0)),
                ('post_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.posttype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctioned_posts', to='schools.school')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'post_type', 'designation', 'subject'), name='unique_sanctioned_post')],
            },
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['school', 'staff_role'], name='staff_staff_school__901e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['school', 'employee_id'], name='staff_staff_school__844b46_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['school', 'is_active'], name='staff_staff_school__791c93_idx'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(fields=('school', 'employee_id'), name='unique_employee_per_school'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(condition=models.Q(('aadhar_number__isnull', False)), fields=('aadhar_number',), name='unique_aadhar_if_present'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_email_if_present'),
        ),
        migrations.AddConstraint(
            model_name='classincharge',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('section',), name='unique_active_incharge_per_section'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['school', 'date'], name='staff_teach_school__49a919_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['teacher', 'date'], name='staff_teach_teacher_71099c_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherattendance',
            constraint=models.UniqueConstraint(fields=('school', 'teacher', 'date'), name='unique_teacher_attendance_per_day'),
        ),
        migrations.AddIndex(
            model_name='teachersubjectassignment',
            index=models.Index(fields=['section'], name='staff_teach_section_8797cf_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubjectassignment',
            index=models.Index(fields=['teacher'], name='staff_teach_teacher_824541_idx'),
        ),
        migrations.AddConstraint(
            model_name='teachersubjectassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'section', 'class_subject'), name='unique_teacher_section_subject'),
        ),
    ]
