# Generated by Django 6.0.4 on 2026-05-24 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_cluster_is_deleted_school_is_deleted_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classincharge',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posttype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sanctionedpost',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classincharge',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='posttype',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='sanctionedpost',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='schools.school'),
        ),
    ]
