# Generated by Django 6.0.4 on 2026-05-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_teachersubjectassignment_alter_classsubject_options_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teachersubjectassignment',
            name='staff_teach_section_8797cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='teachersubjectassignment',
            name='staff_teach_teacher_824541_idx',
        ),
        migrations.RemoveConstraint(
            model_name='teachersubjectassignment',
            name='unique_teacher_section_subject',
        ),
        migrations.DeleteModel(
            name='TeacherSubjectAssignment',
        ),
    ]
