# Generated by Django 6.0.4 on 2026-07-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='max_periods_per_week',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='priority',
        ),
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True, help_text='House number, street, locality, etc.'),
        ),
        migrations.AddField(
            model_name='staff',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='designation',
            field=models.CharField(blank=True, db_index=True, help_text='Official designation of the staff member.', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='pin_code',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Suspended', 'Suspended'), ('Retired', 'Retired'), ('Resigned', 'Resigned'), ('Transferred', 'Transferred')], db_index=True, default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='teaching_experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
