# Generated by Django 6.0.4 on 2026-07-19 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('schools', '0001_initial'),
        ('staff', '0002_remove_staff_max_periods_per_week_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classincharge',
            options={'ordering': ['section__class_obj__display_order', 'section__name'], 'verbose_name': 'Class Incharge', 'verbose_name_plural': 'Class Incharges'},
        ),
        migrations.AddField(
            model_name='classincharge',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='classincharge',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_incharges', to='academics.section'),
        ),
        migrations.AlterField(
            model_name='classincharge',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'staff_role': 'Teaching'}, on_delete=django.db.models.deletion.CASCADE, related_name='class_incharge_assignments', to='staff.staff'),
        ),
        migrations.AddConstraint(
            model_name='classincharge',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('staff',), name='unique_active_section_per_teacher'),
        ),
    ]
