# Generated by Django 6.0.4 on 2026-07-19 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('staff', '0003_alter_classincharge_options_classincharge_remarks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanctionedpost',
            options={'ordering': ['post_type__name']},
        ),
        migrations.RemoveConstraint(
            model_name='sanctionedpost',
            name='unique_sanctioned_post',
        ),
        migrations.RenameField(
            model_name='sanctionedpost',
            old_name='total_posts',
            new_name='sanctioned_posts',
        ),
        migrations.AddField(
            model_name='sanctionedpost',
            name='guest_working',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sanctionedpost',
            name='hkrnl_working',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sanctionedpost',
            name='regular_working',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sanctionedpost',
            name='post_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctioned_posts', to='staff.posttype'),
        ),
        migrations.AddIndex(
            model_name='sanctionedpost',
            index=models.Index(fields=['school', 'post_type'], name='staff_sanct_school__f58d83_idx'),
        ),
        migrations.AddConstraint(
            model_name='sanctionedpost',
            constraint=models.UniqueConstraint(fields=('school', 'post_type'), name='unique_sanctioned_post_per_school'),
        ),
        migrations.RemoveField(
            model_name='sanctionedpost',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='sanctionedpost',
            name='subject',
        ),
    ]
