# Generated by Django 6.0.4 on 2026-07-19 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('staff', '0004_alter_sanctionedpost_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherattendance',
            options={'ordering': ['-date', 'teacher__employee_id'], 'verbose_name': 'Teacher Attendance', 'verbose_name_plural': 'Teacher Attendance'},
        ),
        migrations.RenameIndex(
            model_name='teacherattendance',
            new_name='teacher_att_school_date_idx',
            old_name='staff_teach_school__49a919_idx',
        ),
        migrations.RenameIndex(
            model_name='teacherattendance',
            new_name='teacher_att_teacher_date_idx',
            old_name='staff_teach_teacher_71099c_idx',
        ),
        migrations.RemoveField(
            model_name='teacherattendance',
            name='present',
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave'), ('HALF_DAY', 'Half Day'), ('OFFICIAL_DUTY', 'Official Duty')], db_index=True, default='PRESENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'staff_role': 'Teaching'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance', to='staff.staff'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['school', 'status'], name='teacher_att_school_status_idx'),
        ),
    ]
