# Generated by Django 6.0.4 on 2026-05-09 07:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('schools', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('association_type', models.CharField(choices=[('Club', 'Club'), ('Committee', 'Committee'), ('Nodal', 'Nodal')], db_index=True, max_length=20)),
                ('tasks', models.TextField(blank=True)),
                ('show_on_website', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('chairperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_associations', to='staff.staff')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
                ('documents', models.ManyToManyField(blank=True, related_name='associations', to='documents.document')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='schools.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Association',
                'verbose_name_plural': 'Associations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssociationMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('agenda', models.TextField(blank=True)),
                ('location', models.CharField(max_length=100)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='associations.association')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
                ('minutes_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Association Meeting',
                'verbose_name_plural': 'Association Meetings',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='AssociationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('image', models.ImageField(blank=True, upload_to='association_members/')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='associations.association')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_memberships', to='staff.staff')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Association Member',
                'verbose_name_plural': 'Association Members',
                'ordering': ['designation', 'staff__name'],
            },
        ),
        migrations.CreateModel(
            name='AssociationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='associations.association')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Association Role',
                'verbose_name_plural': 'Association Roles',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ExtracurricularActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Clubs', 'Clubs'), ('Arts', 'Arts'), ('Academic', 'Academic'), ('Community Service', 'Community Service'), ('Other', 'Other')], db_index=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_activities', to='staff.staff')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_activities', to='students.student')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='schools.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Extracurricular Activity',
                'verbose_name_plural': 'Extracurricular Activities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SMCMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Member Secretary', 'Member Secretary'), ('Member', 'Member')], max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('show_on_website', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smc_members', to='schools.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
            ],
            options={
                'verbose_name': 'SMC Member',
                'verbose_name_plural': 'SMC Members',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffAssociationRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_staff', to='associations.associationrole')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_roles', to='staff.staff')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Role Assignment',
                'verbose_name_plural': 'Staff Role Assignments',
            },
        ),
        migrations.CreateModel(
            name='StudentAssociationRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_students', to='associations.associationrole')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_roles', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Student Role Assignment',
                'verbose_name_plural': 'Student Role Assignments',
            },
        ),
        migrations.AddIndex(
            model_name='association',
            index=models.Index(fields=['school', 'association_type'], name='association_school__e1b53a_idx'),
        ),
        migrations.AddConstraint(
            model_name='association',
            constraint=models.UniqueConstraint(fields=('school', 'slug'), name='unique_association_slug_per_school'),
        ),
        migrations.AddConstraint(
            model_name='association',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_association_name_per_school'),
        ),
        migrations.AddIndex(
            model_name='associationmeeting',
            index=models.Index(fields=['association', 'meeting_date'], name='association_associa_135267_idx'),
        ),
        migrations.AddConstraint(
            model_name='associationmember',
            constraint=models.UniqueConstraint(fields=('association', 'staff'), name='unique_member'),
        ),
        migrations.AddConstraint(
            model_name='associationrole',
            constraint=models.UniqueConstraint(fields=('association', 'title'), name='unique_role_per_association'),
        ),
        migrations.AddIndex(
            model_name='extracurricularactivity',
            index=models.Index(fields=['school', 'category'], name='association_school__95c1e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffassociationroleassignment',
            constraint=models.UniqueConstraint(fields=('staff', 'role'), name='unique_staff_role'),
        ),
        migrations.AddConstraint(
            model_name='studentassociationroleassignment',
            constraint=models.UniqueConstraint(fields=('student', 'role'), name='unique_student_role'),
        ),
    ]
