# Generated by Django 6.0.4 on 2026-05-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'ordering': ['-priority', 'name'], 'verbose_name': 'Association', 'verbose_name_plural': 'Associations'},
        ),
        migrations.RemoveConstraint(
            model_name='association',
            name='unique_association_slug_per_school_session',
        ),
        migrations.RemoveConstraint(
            model_name='association',
            name='unique_association_name_per_school_session',
        ),
        migrations.RemoveIndex(
            model_name='association',
            name='association_school__1228e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='association',
            name='association_school__56c1cc_idx',
        ),
        migrations.AlterField(
            model_name='association',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='association',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
