# Generated by Django 6.0.4 on 2026-06-09 03:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('associations', '0001_initial'),
        ('documents', '0001_initial'),
        ('schools', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staffassociationroleassignment',
            name='unique_staff_role_session',
        ),
        migrations.RemoveConstraint(
            model_name='studentassociationroleassignment',
            name='unique_student_role_session',
        ),
        migrations.AlterModelOptions(
            name='associationmeeting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='associationmember',
            options={'ordering': ['member_type'], 'verbose_name': 'Association Member', 'verbose_name_plural': 'Association Members'},
        ),
        migrations.RemoveConstraint(
            model_name='associationmember',
            name='unique_member',
        ),
        migrations.RemoveIndex(
            model_name='associationmeeting',
            name='association_school__6618d2_idx',
        ),
        migrations.RenameField(
            model_name='association',
            old_name='tasks',
            new_name='objectives',
        ),
        migrations.RenameField(
            model_name='associationmember',
            old_name='email',
            new_name='external_email',
        ),
        migrations.RenameField(
            model_name='associationmember',
            old_name='phone_number',
            new_name='external_phone_number',
        ),
        migrations.AddField(
            model_name='associationmeeting',
            name='conducted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
        migrations.AddField(
            model_name='associationmeeting',
            name='meeting_type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid')], default='PHYSICAL', max_length=20),
        ),
        migrations.AddField(
            model_name='associationmeeting',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('POSTPONED', 'Postponed')], default='SCHEDULED', max_length=20),
        ),
        migrations.AddField(
            model_name='associationmeeting',
            name='title',
            field=models.CharField(default=datetime.datetime(2026, 6, 9, 3, 47, 24, 168971, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='associationmember',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='associationmember',
            name='external_designation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='associationmember',
            name='external_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='associationmember',
            name='member_type',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('STUDENT', 'Student'), ('EXTERNAL', 'External')], db_index=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='associationmember',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='association_memberships', to='students.student'),
        ),
        migrations.AddField(
            model_name='associationrole',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='academics.academicsession'),
        ),
        migrations.AlterField(
            model_name='association',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='associationmeeting',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='associationmeeting',
            name='meeting_date',
            field=models.DateTimeField(db_index=True, null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='associationmember',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='association_memberships', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='associationrole',
            name='responsibilities',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='association',
            index=models.Index(fields=['academic_session', 'association_type'], name='association_academi_932f21_idx'),
        ),
        migrations.AddIndex(
            model_name='association',
            index=models.Index(fields=['academic_session', 'status'], name='association_academi_fc8335_idx'),
        ),
        migrations.AddConstraint(
            model_name='association',
            constraint=models.UniqueConstraint(fields=('academic_session', 'school', 'name'), name='unique_association_session'),
        ),
        migrations.AddConstraint(
            model_name='associationmember',
            constraint=models.UniqueConstraint(fields=('academic_session', 'association', 'staff'), name='unique_staff_association_member'),
        ),
        migrations.AddConstraint(
            model_name='associationmember',
            constraint=models.UniqueConstraint(fields=('academic_session', 'association', 'student'), name='unique_student_association_member'),
        ),
        migrations.RemoveField(
            model_name='studentassociationroleassignment',
            name='academic_session',
        ),
        migrations.RemoveField(
            model_name='studentassociationroleassignment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='studentassociationroleassignment',
            name='role',
        ),
        migrations.RemoveField(
            model_name='studentassociationroleassignment',
            name='school',
        ),
        migrations.RemoveField(
            model_name='studentassociationroleassignment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentassociationroleassignment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='associationmember',
            name='designation',
        ),
        migrations.DeleteModel(
            name='StaffAssociationRoleAssignment',
        ),
        migrations.DeleteModel(
            name='StudentAssociationRoleAssignment',
        ),
    ]
