# Generated by Django 6.0.4 on 2026-06-09 07:37

import django.db.models.deletion

from django.conf import settings

from django.db import migrations, models

from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [

        (
            "academics",
            "0002_initial"
        ),

        (
            "associations",
            "0002_remove_staffassociationroleassignment_unique_staff_role_session_and_more"
        ),

        (
            "schools",
            "0001_initial"
        ),

        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),

    ]

    operations = [

        migrations.AlterField(

            model_name="associationmeeting",

            name="meeting_date",

            field=models.DateTimeField(

                db_index=True,

                default=timezone.now,

            ),

            preserve_default=False,
        ),

        migrations.CreateModel(

            name="AssociationRoleAssignment",

            fields=[

                (
                    "id",

                    models.BigAutoField(

                        auto_created=True,

                        primary_key=True,

                        serialize=False,

                        verbose_name="ID",
                    ),
                ),

                (
                    "is_active",

                    models.BooleanField(
                        default=True
                    ),
                ),

                (
                    "is_deleted",

                    models.BooleanField(
                        default=False
                    ),
                ),

                (
                    "created_at",

                    models.DateTimeField(
                        auto_now_add=True
                    ),
                ),

                (
                    "updated_at",

                    models.DateTimeField(
                        auto_now=True
                    ),
                ),

                (
                    "academic_session",

                    models.ForeignKey(

                        blank=True,

                        null=True,

                        on_delete=django.db.models.deletion.CASCADE,

                        related_name="%(class)s_objects",

                        to="academics.academicsession",
                    ),
                ),

                (
                    "created_by",

                    models.ForeignKey(

                        blank=True,

                        null=True,

                        on_delete=django.db.models.deletion.SET_NULL,

                        related_name="+",

                        to=settings.AUTH_USER_MODEL,
                    ),
                ),

                (
                    "member",

                    models.ForeignKey(

                        on_delete=django.db.models.deletion.CASCADE,

                        related_name="role_assignments",

                        to="associations.associationmember",
                    ),
                ),

                (
                    "role",

                    models.ForeignKey(

                        on_delete=django.db.models.deletion.CASCADE,

                        related_name="assigned_members",

                        to="associations.associationrole",
                    ),
                ),

                (
                    "school",

                    models.ForeignKey(

                        blank=True,

                        null=True,

                        on_delete=django.db.models.deletion.CASCADE,

                        related_name="%(class)s_objects",

                        to="schools.school",
                    ),
                ),

                (
                    "updated_by",

                    models.ForeignKey(

                        blank=True,

                        null=True,

                        on_delete=django.db.models.deletion.SET_NULL,

                        related_name="+",

                        to=settings.AUTH_USER_MODEL,
                    ),
                ),

            ],

            options={

                "verbose_name":
                    "Association Role Assignment",

                "verbose_name_plural":
                    "Association Role Assignments",

                "ordering":
                    ["role__title"],

                "constraints": [

                    models.UniqueConstraint(

                        fields=(

                            "academic_session",

                            "member",

                            "role",
                        ),

                        name="unique_member_role_assignment",
                    ),

                    models.UniqueConstraint(

                        fields=(

                            "academic_session",

                            "role",
                        ),

                        name="unique_role_holder_per_session",
                    ),

                ],

            },
        ),

    ]