# Generated by Django 6.0.4 on 2026-05-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0002_alter_association_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smcmember',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='smcmember',
            name='category',
            field=models.CharField(blank=True, choices=[('GEN', 'General'), ('SC', 'Scheduled Caste'), ('BC-A', 'Backward Class - A'), ('BC-B', 'Backward Class - B'), ('EWS', 'Economically Weaker Section'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smcmember',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='smcmember',
            name='nomination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smcmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='smc_photos/'),
        ),
        migrations.AddField(
            model_name='smcmember',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='smcmember',
            name='tenure_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smcmember',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Member (Secretary)', 'Member (Secretary)'), ('Member (Trained Education Scholar)', 'Member (Trained Education Scholar)'), ('Member (Teacher/Student)', 'Member (Teacher/Student)'), ('Member (Parent/Guardian)', 'Member (Parent/Guardian)'), ('Member (General)', 'Member (General)')], max_length=100),
        ),
    ]
