# Generated by Django 6.0.4 on 2026-06-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0003_alter_associationmeeting_meeting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracurricularactivity',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
