# Generated by Django 6.0.4 on 2026-05-31 10:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('session', models.CharField(db_index=True, max_length=20)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rcf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cwf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ccwf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='schools.school')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.stream')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('session', models.CharField(db_index=True, max_length=20)),
                ('is_closed', models.BooleanField(db_index=True, default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='finance.feestructure')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Online', 'Online'), ('Cheque', 'Cheque')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Success', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fee_payments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='schools.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.studentfee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['session'], name='finance_fee_session_232929_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['school'], name='finance_fee_school__a3f6b8_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['is_active'], name='finance_fee_is_acti_595955_idx'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('school', 'class_obj', 'stream', 'session'), name='unique_fee_structure_per_class_stream_session'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.CheckConstraint(condition=models.Q(('admission_fee__gte', 0)), name='admission_fee_positive'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.CheckConstraint(condition=models.Q(('rcf__gte', 0)), name='rcf_positive'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.CheckConstraint(condition=models.Q(('cwf__gte', 0)), name='cwf_positive'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.CheckConstraint(condition=models.Q(('ccwf__gte', 0)), name='ccwf_positive'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.CheckConstraint(condition=models.Q(('other_fee__gte', 0)), name='other_fee_positive'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['session'], name='finance_stu_session_7704ea_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['school'], name='finance_stu_school__7e89c1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['is_closed'], name='finance_stu_is_clos_ab0232_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='unique_student_fee'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='student_fee_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='student_fee_paid_positive'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.CheckConstraint(condition=models.Q(('due_amount__gte', 0)), name='student_fee_due_positive'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['payment_date'], name='finance_fee_payment_863cf5_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['receipt_number'], name='finance_fee_receipt_ca3131_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['school'], name='finance_fee_school__ebd415_idx'),
        ),
        migrations.AddConstraint(
            model_name='feepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fee_payment_amount_positive'),
        ),
    ]
