# Generated by Django 6.0.4 on 2026-05-17 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_classroom_options_alter_medium_options_and_more'),
        ('finance', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0004_rename_studentachievement_achievement_achiever_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='feepayment',
            name='unique_transaction_id',
        ),
        migrations.RemoveConstraint(
            model_name='feestructure',
            name='unique_fee_structure_per_session',
        ),
        migrations.RemoveConstraint(
            model_name='studentfee',
            name='unique_fee_per_student_per_session',
        ),
        migrations.RemoveIndex(
            model_name='feestructure',
            name='finance_fee_school__9cfb16_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentfee',
            name='finance_stu_student_bf9d27_idx',
        ),
        migrations.AddField(
            model_name='feepayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fee_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Success', max_length=20),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='schools.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='school',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='schools.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Online', 'Online'), ('Cheque', 'Cheque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='receipt_number',
            field=models.CharField(db_index=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.stream'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['receipt_number'], name='finance_fee_receipt_ca3131_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['school'], name='finance_fee_school__ebd415_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['school'], name='finance_fee_school__a3f6b8_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['is_active'], name='finance_fee_is_acti_595955_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['school'], name='finance_stu_school__7e89c1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['is_closed'], name='finance_stu_is_clos_ab0232_idx'),
        ),
        migrations.AddConstraint(
            model_name='feepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fee_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('school', 'class_obj', 'stream', 'session'), name='unique_fee_structure_per_class_stream_session'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.CheckConstraint(condition=models.Q(('admission_fee__gte', 0)), name='admission_fee_positive'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.CheckConstraint(condition=models.Q(('rcf__gte', 0)), name='rcf_positive'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.CheckConstraint(condition=models.Q(('cwf__gte', 0)), name='cwf_positive'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.CheckConstraint(condition=models.Q(('ccwf__gte', 0)), name='ccwf_positive'),
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.CheckConstraint(condition=models.Q(('other_fee__gte', 0)), name='other_fee_positive'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='unique_student_fee'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='student_fee_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='student_fee_paid_positive'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.CheckConstraint(condition=models.Q(('due_amount__gte', 0)), name='student_fee_due_positive'),
        ),
    ]
