# Generated by Django 6.0.4 on 2026-06-06 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),

                # ======================================
                # BASIC INFORMATION
                # ======================================

                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255,
                        unique=True,
                        blank=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                    ),
                ),

                # ======================================
                # CRC INFORMATION
                # ======================================

                (
                    "crc_name",
                    models.CharField(
                        max_length=255,
                    ),
                ),
                (
                    "crc_designation",
                    models.CharField(
                        max_length=100,
                        blank=True,
                    ),
                ),
                (
                    "crc_phone",
                    models.CharField(
                        max_length=20,
                        blank=True,
                    ),
                ),
                (
                    "crc_email",
                    models.EmailField(
                        max_length=254,
                        blank=True,
                        null=True,
                    ),
                ),

                # ======================================
                # OFFICE CONTACT
                # ======================================

                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        blank=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                    ),
                ),

                # ======================================
                # STATUS
                # ======================================

                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                    ),
                ),

                # ======================================
                # AUDIT
                # ======================================

                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "clusters",
                "verbose_name": "Cluster",
                "verbose_name_plural": "Clusters",
                "ordering": ["name"],
            },
        ),

        migrations.AddConstraint(
            model_name="cluster",
            constraint=models.UniqueConstraint(
                fields=("email",),
                condition=models.Q(email__isnull=False),
                name="unique_cluster_email_if_present",
            ),
        ),

        migrations.AddConstraint(
            model_name="cluster",
            constraint=models.UniqueConstraint(
                fields=("crc_email",),
                condition=models.Q(crc_email__isnull=False),
                name="unique_crc_email_if_present",
            ),
        ),

        migrations.AddIndex(
            model_name="cluster",
            index=models.Index(
                fields=["is_active"],
                name="cluster_is_active_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="cluster",
            index=models.Index(
                fields=["is_deleted"],
                name="cluster_is_deleted_idx",
            ),
        ),
    ]