# Generated by Django 6.0.4 on 2026-07-19 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Cluster Name', max_length=255, unique=True)),
                ('code', models.CharField(help_text='Unique Cluster Code', max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the cluster')),
                ('crc_name', models.CharField(help_text='CRC Coordinator/Incharge Name', max_length=255)),
                ('crc_designation', models.CharField(blank=True, help_text='CRC Coordinator Designation', max_length=100)),
                ('crc_phone', models.CharField(blank=True, help_text='CRC Mobile Number', max_length=20)),
                ('crc_email', models.EmailField(blank=True, help_text='CRC Email Address', max_length=254, null=True)),
                ('email', models.EmailField(blank=True, help_text='Official Cluster Email', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Official Cluster Contact Number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Cluster Office Address')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
                'db_table': 'clusters',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='clusters_is_acti_5ca7de_idx'), models.Index(fields=['is_deleted'], name='clusters_is_dele_844a9a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_cluster_email_if_present'), models.UniqueConstraint(condition=models.Q(('crc_email__isnull', False)), fields=('crc_email',), name='unique_crc_email_if_present')],
            },
        ),
    ]
