# Generated by Django 6.0.4 on 2026-07-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_cluster_deleted_at_cluster_deleted_by'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cluster',
            new_name='clusters_is_acti_5ca7de_idx',
            old_name='cluster_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='cluster',
            new_name='clusters_is_dele_844a9a_idx',
            old_name='cluster_is_deleted_idx',
        ),
        migrations.AlterField(
            model_name='cluster',
            name='address',
            field=models.TextField(blank=True, help_text='Cluster Office Address'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='code',
            field=models.CharField(help_text='Unique Cluster Code', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='crc_designation',
            field=models.CharField(blank=True, help_text='CRC Coordinator Designation', max_length=100),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='crc_email',
            field=models.EmailField(blank=True, help_text='CRC Email Address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='crc_name',
            field=models.CharField(help_text='CRC Coordinator/Incharge Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='crc_phone',
            field=models.CharField(blank=True, help_text='CRC Mobile Number', max_length=20),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the cluster'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='email',
            field=models.EmailField(blank=True, help_text='Official Cluster Email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='name',
            field=models.CharField(help_text='Cluster Name', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='phone',
            field=models.CharField(blank=True, help_text='Official Cluster Contact Number', max_length=20),
        ),
    ]
