# Generated by Django 6.0.4 on 2026-05-25 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_module'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='permission',
            name='accounts_pe_module_1658a5_idx',
        ),
        migrations.AddField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('add', 'Add'), ('edit', 'Edit'), ('delete', 'Delete'), ('import', 'Import'), ('export', 'Export'), ('assign', 'Assign'), ('approve', 'Approve')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.module'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('module', 'action')},
        ),
    ]
