# Generated by Django 6.0.4 on 2026-05-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_permission_accounts_pe_module_1658a5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='permission',
            name='accounts_pe_code_3a265a_idx',
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
