# Generated by Django 6.0.4 on 2026-05-26 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_module_options_remove_module_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permission',
            table='auth_permissions',
        ),
    ]
