# Generated by Django 6.0.4 on 2026-05-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_permission_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ['role__name']},
        ),
    ]
