# Generated by Django 6.0.4 on 2026-05-19 11:00

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0002_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'staff_role': 'Teaching'}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='schools.school'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_entries', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='teacher_subject_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.teachersubjectassignment'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='academics.day'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.timetableslot'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_class_per_school'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_classroom_per_school'),
        ),
        migrations.AddConstraint(
            model_name='day',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_day_per_school'),
        ),
        migrations.AddConstraint(
            model_name='day',
            constraint=models.UniqueConstraint(fields=('school', 'sequence'), name='unique_day_sequence_per_school'),
        ),
        migrations.AddConstraint(
            model_name='medium',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_medium_per_school'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_stream_per_school'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('school', 'class_obj', 'name'), name='unique_section_per_class_per_school'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('school'), name='unique_subject_per_school_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(fields=('school', 'class_obj', 'stream', 'subject', 'sub_stream'), name='unique_class_subject'),
        ),
        migrations.AddIndex(
            model_name='teachersubjectassignment',
            index=models.Index(fields=['section'], name='academics_t_section_1af4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubjectassignment',
            index=models.Index(fields=['teacher'], name='academics_t_teacher_cacaea_idx'),
        ),
        migrations.AddConstraint(
            model_name='teachersubjectassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'section', 'class_subject'), name='unique_teacher_section_subject'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('school', 'day', 'sequence_number'), name='unique_slot_sequence_per_day'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(condition=models.Q(('period_number__isnull', False)), fields=('school', 'day', 'period_number'), name='unique_period_per_day'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['slot'], name='academics_t_slot_id_4ca569_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['school', 'slot'], name='academics_t_school__fc419c_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('slot', 'teacher_subject_assignment'), name='unique_assignment_per_slot'),
        ),
    ]
