# Generated by Django 6.0.4 on 2026-05-09 07:15

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='substitute_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'staff_role': 'Teaching'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_entries', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='teacher_subject_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='staff.teachersubjectassignment'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.day'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.timetableslot'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_class_per_school'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_classroom_per_school'),
        ),
        migrations.AddConstraint(
            model_name='day',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_day_per_school'),
        ),
        migrations.AddConstraint(
            model_name='day',
            constraint=models.UniqueConstraint(fields=('school', 'sequence'), name='unique_day_sequence_per_school'),
        ),
        migrations.AddConstraint(
            model_name='medium',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_medium_per_school'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_stream_per_school'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['school', 'class_obj'], name='academics_s_school__ca9be6_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['school', 'name'], name='academics_s_school__b68ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['school', 'stream'], name='academics_s_school__b3c66b_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['school', 'medium'], name='academics_s_school__8eb447_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['class_obj', 'name'], name='academics_s_class_o_661ef0_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(condition=models.Q(('medium__isnull', True), ('stream__isnull', True), ('sub_stream__isnull', True)), fields=('school', 'class_obj', 'name'), name='unique_section_basic'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(condition=models.Q(('stream__isnull', False), ('sub_stream__isnull', True)), fields=('school', 'class_obj', 'name', 'stream'), name='unique_section_stream_only'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(condition=models.Q(('stream__isnull', False), ('sub_stream__isnull', False)), fields=('school', 'class_obj', 'name', 'stream', 'sub_stream'), name='unique_section_substream'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(condition=models.Q(('medium__isnull', False), ('stream__isnull', True), ('sub_stream__isnull', True)), fields=('school', 'class_obj', 'name', 'medium'), name='unique_section_medium'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.CheckConstraint(condition=models.Q(('sub_stream__isnull', True), ('stream__isnull', False), _connector='OR'), name='substream_requires_stream'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('school'), name='unique_subject_per_school_case_insensitive'),
        ),
        migrations.AddIndex(
            model_name='classsubject',
            index=models.Index(fields=['class_obj', 'stream'], name='class_subje_class_o_105df2_idx'),
        ),
        migrations.AddIndex(
            model_name='classsubject',
            index=models.Index(fields=['class_obj', 'subject'], name='class_subje_class_o_1ee343_idx'),
        ),
        migrations.AddIndex(
            model_name='classsubject',
            index=models.Index(fields=['class_obj', 'stream', 'subject'], name='class_subje_class_o_666fb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(fields=('class_obj', 'stream', 'sub_stream', 'subject'), name='unique_class_subject_mapping'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.CheckConstraint(condition=models.Q(('theory_periods_per_week__gte', 0)), name='theory_periods_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.CheckConstraint(condition=models.Q(('practical_periods_per_week__gte', 0)), name='practical_periods_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.CheckConstraint(condition=models.Q(('theory_periods_per_week__gt', 0), ('practical_periods_per_week__gt', 0), _connector='OR'), name='at_least_one_period'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.CheckConstraint(condition=models.Q(('sub_stream__in', ['Medical', 'Non-Medical', 'Vocational']), ('sub_stream__isnull', True), _connector='OR'), name='valid_sub_stream'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.CheckConstraint(condition=models.Q(('has_lab', False), ('practical_periods_per_week__gt', 0), _connector='OR'), name='lab_requires_practical'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['school', 'day'], name='timetable_s_school__4af272_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('school', 'day', 'sequence_number'), name='unique_slot_sequence_per_day'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(condition=models.Q(('period_number__isnull', False)), fields=('school', 'day', 'period_number'), name='unique_period_per_day'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='valid_time_range'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['slot'], name='timetable_e_slot_id_e696bf_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['teacher_subject_assignment'], name='timetable_e_teacher_a9b626_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('teacher_subject_assignment', 'slot'), name='unique_teacher_slot'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(condition=models.Q(('classroom__isnull', False)), fields=('classroom', 'slot'), name='unique_classroom_slot'),
        ),
    ]
