# Generated by Django 6.0.4 on 2026-07-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name']},
        ),
    ]
