# Generated by Django 6.0.4 on 2026-06-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
