# Generated by Django 6.0.4 on 2026-05-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_subject_has_lab_subject_is_language_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classroom',
            name='unique_classroom_per_school',
        ),
    ]
