# Generated by Django 6.0.4 on 2026-05-12 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_classsubject_options_and_more'),
        ('schools', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='classsubject',
            options={'ordering': ['class_obj__class_order', 'subject__name']},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['slot__day__sequence', 'slot__sequence_number']},
        ),
        migrations.AlterModelOptions(
            name='timetableslot',
            options={'ordering': ['day__sequence', 'sequence_number']},
        ),
        migrations.AddField(
            model_name='classsubject',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='schools.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='academics.classroom'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='academics.day'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='schools.school'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(fields=('school', 'class_obj', 'stream', 'subject', 'sub_stream'), name='unique_class_subject'),
        ),
        migrations.AddConstraint(
            model_name='day',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_day_per_school'),
        ),
        migrations.AddConstraint(
            model_name='day',
            constraint=models.UniqueConstraint(fields=('school', 'sequence'), name='unique_day_sequence_per_school'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(fields=('school', 'day', 'sequence_number'), name='unique_slot_sequence_per_day'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.UniqueConstraint(condition=models.Q(('period_number__isnull', False)), fields=('school', 'day', 'period_number'), name='unique_period_per_day'),
        ),
        migrations.AlterModelTable(
            name='classsubject',
            table='class_subjects',
        ),
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.classsubject'),
        ),
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academics.section'),
        ),
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'staff_role': 'Teaching'}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teacher_subject_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.teachersubjectassignment'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('slot', 'teacher_subject_assignment'), name='unique_assignment_per_slot'),
        ),
        migrations.AddIndex(
            model_name='teachersubjectassignment',
            index=models.Index(fields=['section'], name='academics_t_section_1af4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubjectassignment',
            index=models.Index(fields=['teacher'], name='academics_t_teacher_cacaea_idx'),
        ),
        migrations.AddConstraint(
            model_name='teachersubjectassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'section', 'class_subject'), name='unique_teacher_section_subject'),
        ),
    ]
