# Generated by Django 6.0.4 on 2026-07-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_class_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['display_order', 'name']},
        ),
    ]
