# Generated by Django 6.0.4 on 2026-05-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_teachersubjectassignment_alter_classsubject_options_and_more'),
        ('schools', '0001_initial'),
        ('staff', '0003_alter_staff_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='medium',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['slot__day__sequence', 'slot__period_number']},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='medium',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['slot'], name='academics_t_slot_id_4ca569_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['school', 'slot'], name='academics_t_school__fc419c_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('school', 'class_obj', 'name'), name='unique_section_per_class_per_school'),
        ),
    ]
