# Generated by Django 6.0.4 on 2026-05-30 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_section_classroom_and_more'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['class_obj__display_order', 'name']},
        ),
        migrations.RenameField(
            model_name='class',
            old_name='class_order',
            new_name='display_order',
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school', 'display_order'], name='academics_c_school__da4ccf_idx'),
        ),
    ]
