# Generated by Django 6.0.4 on 2026-05-31 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_class_options_alter_section_options_and_more'),
        ('infrastructure', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['school', 'class_obj'], name='academics_s_school__ca9be6_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['school', 'name'], name='academics_s_school__b68ce6_idx'),
        ),
    ]
