# Generated by Django 6.0.4 on 2026-05-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
