# Generated by Django 6.0.4 on 2026-06-07 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['classroom_code'], 'verbose_name': 'Classroom', 'verbose_name_plural': 'Classrooms'},
        ),
        migrations.RemoveConstraint(
            model_name='classroom',
            name='unique_classroom_per_school',
        ),
        migrations.AddField(
            model_name='classroom',
            name='air_conditioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroom',
            name='classroom_code',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='internet_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroom',
            name='projector_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='infrastructure.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='smart_classroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroom',
            name='whiteboard_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='infrastructure.floor'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('school', 'classroom_code'), name='unique_school_classroom_code'),
        ),
        migrations.AlterModelTable(
            name='classroom',
            table='classrooms',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='name',
        ),
    ]
