# Generated by Django 6.0.4 on 2026-06-09 03:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_alter_classroom_options_and_more'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classroom_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['school'], name='classrooms_school__8fee6e_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['classroom_code'], name='classrooms_classro_574e04_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['floor'], name='classrooms_floor_i_0af17f_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['is_active'], name='classrooms_is_acti_148ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['is_deleted'], name='classrooms_is_dele_fdcdce_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('school', 'room'), name='unique_school_classroom_room'),
        ),
    ]
