# Generated by Django 6.0.4 on 2026-06-10 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_alter_classroom_classroom_code_and_more'),
        ('schools', '0002_aboutschool_deleted_at_aboutschool_deleted_by_and_more'),
        ('staff', '0002_classincharge_deleted_at_classincharge_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['asset_code'], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['classroom_code']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['building', 'floor', 'room_number'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.RemoveConstraint(
            model_name='classroom',
            name='unique_school_classroom_room',
        ),
        migrations.RemoveIndex(
            model_name='classroom',
            name='classrooms_school__8fee6e_idx',
        ),
        migrations.RemoveIndex(
            model_name='classroom',
            name='classrooms_classro_574e04_idx',
        ),
        migrations.RemoveIndex(
            model_name='classroom',
            name='classrooms_floor_i_0af17f_idx',
        ),
        migrations.AddField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='building',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facility',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='floor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='library',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playground',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playground',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='auditorium_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='building',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='lab_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='library',
            name='library_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_code'], name='assets_asset_c_4e968f_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_status_326766_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category'], name='assets_categor_840335_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorium',
            index=models.Index(fields=['auditorium_code'], name='auditoriums_auditor_b0099c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorium',
            index=models.Index(fields=['room'], name='auditoriums_room_id_5ab877_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['code'], name='buildings_code_9f4030_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['name'], name='buildings_name_0d2a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['school', 'classroom_code'], name='classrooms_school__294cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['facility_type'], name='facilities_facilit_ab2628_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['available'], name='facilities_availab_8378c6_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['school'], name='facilities_school__0232c6_idx'),
        ),
        migrations.AddIndex(
            model_name='floor',
            index=models.Index(fields=['building'], name='floors_buildin_473a97_idx'),
        ),
        migrations.AddIndex(
            model_name='floor',
            index=models.Index(fields=['floor_number'], name='floors_floor_n_6edbda_idx'),
        ),
        migrations.AddIndex(
            model_name='floor',
            index=models.Index(fields=['school'], name='floors_school__31a48e_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratory',
            index=models.Index(fields=['school'], name='laboratorie_school__d1b44e_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratory',
            index=models.Index(fields=['lab_code'], name='laboratorie_lab_cod_6cd336_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratory',
            index=models.Index(fields=['lab_type'], name='laboratorie_lab_typ_914981_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratory',
            index=models.Index(fields=['room'], name='laboratorie_room_id_524613_idx'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['school'], name='libraries_school__fd2886_idx'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['library_code'], name='libraries_library_0ac690_idx'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['room'], name='libraries_room_id_f373f0_idx'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['librarian'], name='libraries_librari_c20efc_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['asset'], name='maintenance_asset_i_5662cc_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['maintenance_date'], name='maintenance_mainten_27e564_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['next_due_date'], name='maintenance_next_du_976d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['service_type'], name='maintenance_service_6031fe_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['school'], name='maintenance_school__6a3b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='playground',
            index=models.Index(fields=['school'], name='playgrounds_school__a28165_idx'),
        ),
        migrations.AddIndex(
            model_name='playground',
            index=models.Index(fields=['playground_type'], name='playgrounds_playgro_73d041_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['school'], name='rooms_school__86870d_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['building'], name='rooms_buildin_aa2351_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['floor'], name='rooms_floor_i_d969d3_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type'], name='rooms_room_ty_7b8350_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_number'], name='rooms_room_nu_5c8eca_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_active'], name='rooms_is_acti_b7cb02_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_deleted'], name='rooms_is_dele_0a2bef_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('school', 'asset_code'), name='unique_school_asset_code'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('school', 'serial_number'), name='unique_school_asset_serial_number'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_school_asset_category_code'),
        ),
        migrations.AddConstraint(
            model_name='auditorium',
            constraint=models.UniqueConstraint(fields=('school', 'auditorium_code'), name='unique_school_auditorium_code'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_school_building_code'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_school_facility_name'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('building', 'name'), name='unique_floor_name_per_building'),
        ),
        migrations.AddConstraint(
            model_name='laboratory',
            constraint=models.UniqueConstraint(fields=('school', 'lab_code'), name='unique_school_lab_code'),
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(fields=('school', 'library_code'), name='unique_school_library_code'),
        ),
        migrations.AddConstraint(
            model_name='playground',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_school_playground_name'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('building', 'room_number'), name='unique_room_number_per_building'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('building', 'room_name'), name='unique_room_name_per_building'),
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='floor',
        ),
    ]
