# Generated by Django 6.0.4 on 2026-05-19 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('schools', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Enter student name', max_length=200)),
                ('achievement_type', models.CharField(choices=[('sports', 'Sports'), ('cultural', 'Cultural Activity'), ('competition', 'Competition'), ('exam', 'Final Exam'), ('quiz', 'Quiz')], max_length=20)),
                ('event_name', models.CharField(blank=True, help_text='Name of event/activity/exam', max_length=200, null=True)),
                ('rank', models.CharField(blank=True, help_text='e.g. 1st, 2nd, Winner', max_length=50, null=True)),
                ('reward_title', models.CharField(blank=True, help_text='Certificate/Medal/Award Title', max_length=200, null=True)),
                ('date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Achiever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=7)),
                ('achievement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students_Achievement', to='students.achievement')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('srn', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('school_code', models.CharField(blank=True, max_length=20, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('roll_number', models.IntegerField(blank=True, null=True)),
                ('admission_number', models.CharField(blank=True, max_length=20, null=True)),
                ('full_name_aadhar', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('domicile_of_haryana', models.CharField(blank=True, max_length=100, null=True)),
                ('father_full_name_aadhar', models.CharField(blank=True, max_length=255, null=True)),
                ('father_aadhaar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_full_name_aadhar', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_aadhaar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('father_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('family_annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('block', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_district', models.CharField(blank=True, max_length=100, null=True)),
                ('city_village_town', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('subjects_opted', models.TextField(blank=True, help_text='Format: Optional:Math, Compulsory:English', null=True)),
                ('subjects', models.TextField(blank=True, null=True)),
                ('caste', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('disability', models.CharField(blank=True, max_length=255, null=True)),
                ('disorder', models.CharField(blank=True, max_length=100, null=True)),
                ('below_poverty_line_certificate_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bpl_certificate_issuing_authority', models.CharField(blank=True, max_length=255, null=True)),
                ('family_id', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.section')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.stream')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.class')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['school'], name='students_st_school__196ea5_idx'), models.Index(fields=['section'], name='students_st_section_bd539f_idx')],
            },
        ),
    ]
