# Generated by Django 6.0.4 on 2026-05-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_students_st_section_0637a8_idx_students_st_section_bd539f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
