# Generated by Django 6.0.4 on 2026-05-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_achievement_options_alter_achiever_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='achiever',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
