# Generated by Django 6.0.4 on 2026-05-17 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentAchievement',
            new_name='Achievement',
        ),
        migrations.CreateModel(
            name='Achiever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=7)),
                ('achievement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students_Achievement', to='students.achievement')),
            ],
        ),
        migrations.DeleteModel(
            name='ExamDetail',
        ),
    ]
