# Generated by Django 6.0.4 on 2026-06-10 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationcategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communicationcategory',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='schools.school'),
        ),
        migrations.AddField(
            model_name='communicationcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='schools.school'),
        ),
        migrations.AddField(
            model_name='communicationtemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_objects', to='schools.school'),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communicationcategory',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AddIndex(
            model_name='circular',
            index=models.Index(fields=['school', 'issue_date'], name='circulars_school__92b402_idx'),
        ),
        migrations.AddIndex(
            model_name='circular',
            index=models.Index(fields=['school', 'circular_type'], name='circulars_school__b5570b_idx'),
        ),
        migrations.AddIndex(
            model_name='circular',
            index=models.Index(fields=['school', 'is_active'], name='circulars_school__098907_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationcategory',
            index=models.Index(fields=['school', 'name'], name='communicati_school__12374c_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationcategory',
            index=models.Index(fields=['school', 'code'], name='communicati_school__c6e15d_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['school', 'start_date'], name='events_school__595ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['school', 'is_published'], name='events_school__3ca365_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['school', 'publish_date'], name='news_school__1c3698_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['school', 'is_published'], name='news_school__6ddde8_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['school', 'slug'], name='news_school__795b97_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['school', 'publish_date'], name='notices_school__ff1ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['school', 'notice_type'], name='notices_school__4c8529_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['school', 'is_published'], name='notices_school__ecba66_idx'),
        ),
        migrations.AddConstraint(
            model_name='circular',
            constraint=models.UniqueConstraint(fields=('school', 'title'), name='unique_circular_title_per_school'),
        ),
        migrations.AddConstraint(
            model_name='communicationcategory',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_communication_category_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='communicationcategory',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_communication_category_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='communicationtemplate',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_template_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('school', 'title'), name='unique_event_title_per_school'),
        ),
        migrations.AddConstraint(
            model_name='news',
            constraint=models.UniqueConstraint(fields=('school', 'title'), name='unique_news_title_per_school'),
        ),
        migrations.AddConstraint(
            model_name='news',
            constraint=models.UniqueConstraint(fields=('school', 'slug'), name='unique_news_slug_per_school'),
        ),
        migrations.AddConstraint(
            model_name='notice',
            constraint=models.UniqueConstraint(fields=('school', 'title'), name='unique_notice_title_per_school'),
        ),
    ]
